version: "3.5"
services:
  demo:
    image: demo:0.0.1-SNAPSHOT
    ports:
      - "8080:8080"
    networks:
      - demo-database
    depends_on:
      - mysqldb
 
  mysqldb:
    image: mysql:8
    networks:
      - demo-database
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=db_example  

networks:
  demo-database: 